[tasks.clippy-ebpf-json]
workspace = false
env = { AYA_BUILD_SKIP = true }
toolchain = "nightly"
command = "cargo"
args = [
  "clippy",
  "-Zbuild-std",
  "--release",
  "--target=bpfel-unknown-none",
  "--manifest-path=kunai-ebpf/Cargo.toml",
  "--message-format=json"
]

[tasks.clippy-json]
workspace = false
toolchain = "nightly"
dependencies = ["clippy-ebpf-json"]
command = "cargo"
args = ["clippy", "--all-targets", "--message-format=json"]

[tasks.clippy-ebpf]
workspace = false
env = { AYA_BUILD_SKIP = true }
toolchain = "nightly"
command = "cargo"
args = [
  "clippy",
  "-Zbuild-std",
  "--release",
  "--target=bpfel-unknown-none",
  "--manifest-path=kunai-ebpf/Cargo.toml",
]

[tasks.clippy]
workspace = false
toolchain = "nightly"
dependencies = ["clippy-ebpf"]
command = "cargo"
args = ["clippy", "--all-targets"]
