[alias]
# throw kunai ;)
tk = "run --config .cargo/sudo-runner.toml --bin kunai"

[target."cfg(target_env = \"musl\")"]
# to cross compile without having to pass linker via RUSTFLAGS variable
linker = "lld"
